"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import Link from "next/link";
import {
  ChevronLeft,
  Upload,
  Wand2,
  ShieldCheck,
  Loader2,
  Sparkles,
  CheckCircle2,
} from "lucide-react";

const PIPE = [
  { key: "upload", label: "Upload RFP", icon: Upload },
  { key: "extract", label: "Schema extraction", icon: Wand2 },
  { key: "review", label: "Schema review", icon: ShieldCheck },
] as const;

export default function NewTenderPage() {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [stage, setStage] = useState<(typeof PIPE)[number]["key"]>("upload");

  async function simulate() {
    setBusy(true);
    setStage("upload");
    await new Promise((r) => setTimeout(r, 700));
    setStage("extract");
    await new Promise((r) => setTimeout(r, 1300));
    setStage("review");
    await new Promise((r) => setTimeout(r, 700));
    router.push("/tenders");
  }

  return (
    <div className="mx-auto w-full max-w-[820px] space-y-6">
      <Link
        href="/tenders"
        className="inline-flex items-center gap-1.5 text-[13px] font-medium text-ink-500 hover:text-ink-800"
      >
        <ChevronLeft className="h-4 w-4" /> All tenders
      </Link>

      <header>
        <h1 className="h-title">New tender</h1>
        <p className="h-sub mt-1">
          Upload the RFP. Claude extracts a structured comparison schema in
          ~20 seconds. You review and approve before bids are loaded.
        </p>
      </header>

      <div className="grid gap-3 sm:grid-cols-3">
        {PIPE.map((p, i) => {
          const Icon = p.icon;
          const active = stage === p.key;
          const done = PIPE.findIndex((x) => x.key === stage) > i;
          return (
            <motion.div
              key={p.key}
              initial={{ opacity: 0, y: 6 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.07 }}
              className={`relative overflow-hidden rounded-2xl border bg-white p-4 shadow-soft transition ${
                active
                  ? "border-violet-300 ring-4 ring-violet-100"
                  : done
                  ? "border-emerald-200"
                  : "border-ink-200/70"
              }`}
            >
              <div className="flex items-center gap-2">
                <span
                  className={`grid h-9 w-9 place-items-center rounded-xl ${
                    active
                      ? "bg-violet-50 text-violet-600"
                      : done
                      ? "bg-emerald-50 text-emerald-600"
                      : "bg-ink-50 text-ink-500"
                  }`}
                >
                  {active ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : done ? (
                    <CheckCircle2 className="h-4 w-4" />
                  ) : (
                    <Icon className="h-4 w-4" />
                  )}
                </span>
                <div>
                  <p className="text-[11px] font-medium uppercase tracking-wide text-ink-400">
                    Step {i + 1}
                  </p>
                  <p className="text-[13px] font-semibold text-ink-900">{p.label}</p>
                </div>
              </div>
              {active ? (
                <div className="absolute inset-x-0 bottom-0 h-px overflow-hidden">
                  <div className="shimmer h-full w-full" />
                </div>
              ) : null}
            </motion.div>
          );
        })}
      </div>

      <div className="rounded-2xl border border-ink-200/70 bg-white p-6 shadow-soft">
        <form className="grid gap-4 sm:grid-cols-2">
          <Field label="Tender name" placeholder="Enterprise Data Center Migration" />
          <Field label="Reference" placeholder="RFP-2034-18" />
          <Field label="Category" placeholder="IT — Cloud & Infrastructure" />
          <Field label="Budget (USD)" placeholder="2,500,000" />
        </form>

        <div className="mt-5 rounded-2xl border border-dashed border-violet-300 bg-violet-50/40 p-6 text-center">
          <Sparkles className="mx-auto h-6 w-6 text-violet-600" />
          <p className="mt-2 text-[13px] font-semibold text-ink-900">
            Drag the RFP PDF here, or click to choose
          </p>
          <p className="text-[12px] text-ink-500">
            PDF, DOCX or ZIP · up to 50 MB · we never train on your tender data
          </p>
        </div>

        <div className="mt-5 flex items-center justify-between">
          <p className="text-[11px] text-ink-500">
            Schema generated by Claude Sonnet 4.6. You review and approve before bids are loaded.
          </p>
          <button
            type="button"
            disabled={busy}
            onClick={simulate}
            className="btn-primary"
          >
            {busy ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" /> Working…
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4" /> Extract schema
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

function Field({ label, placeholder }: { label: string; placeholder: string }) {
  return (
    <label className="block">
      <span className="label">{label}</span>
      <input type="text" placeholder={placeholder} className="input-text mt-1.5" />
    </label>
  );
}
