import { NextResponse } from "next/server";
import { getTender } from "@/lib/data";
import crypto from "node:crypto";

export async function GET(
  _req: Request,
  { params }: { params: { id: string } },
) {
  const tender = await getTender(params.id);
  if (!tender) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }

  // Hash-chain the audit trail so the pack is tamper-evident.
  let prevHash = "";
  const chain = tender.audit
    .slice()
    .reverse()
    .map((e) => {
      const payload = JSON.stringify({
        prev: prevHash,
        at: e.createdAt,
        action: e.action,
        actor: e.actor,
        target: e.target,
        summary: e.summary,
      });
      const hash = crypto.createHash("sha256").update(payload).digest("hex");
      prevHash = hash;
      return {
        at: e.createdAt,
        action: e.action,
        actor: e.actor,
        actorRole: e.actorRole,
        target: e.target,
        summary: e.summary,
        hash,
      };
    });

  const pack = {
    generatedAt: new Date().toISOString(),
    generatedBy: "BidLens",
    tender: {
      id: tender.id,
      name: tender.name,
      reference: tender.reference,
      stage: tender.stage,
      client: tender.client,
      issuedAt: tender.issuedAt,
      closingAt: tender.closingAt,
      owner: tender.ownerName,
      budget: tender.budget,
      currency: tender.currency,
      description: tender.description,
      weights: {
        technical: tender.weightTechnical,
        commercial: tender.weightCommercial,
        delivery: tender.weightDelivery,
        localContent: tender.weightLocalContent,
      },
    },
    schema: tender.schema
      ? {
          version: tender.schema.version,
          approvedBy: tender.schema.approvedBy,
          approvedAt: tender.schema.approvedAt,
          scopeItems: tender.schema.scopeItems,
          mandatoryTCs: tender.schema.mandatoryTCs,
          evaluationCriteria: tender.schema.evaluationCriteria,
          pricingStructure: tender.schema.pricingStructure,
        }
      : null,
    committee: tender.committee.map((c) => ({
      name: c.fullName,
      role: c.role,
      email: c.email,
      weightShare: c.weightShare,
      hasSubmitted: c.hasSubmitted,
    })),
    bids: tender.bids.map((b) => ({
      vendor: b.vendorName,
      submittedAt: b.submittedAt,
      totalPrice: b.totalPrice,
      currency: b.currency,
      validityDays: b.validityDays,
      compliance: b.complianceLevel,
      overallScore: b.overallScore,
      scoreBreakdown: {
        technical: b.scoreTechnical,
        commercial: b.scoreCommercial,
        delivery: b.scoreDelivery,
        localContent: b.scoreLocalContent,
      },
      strengths: b.strengths,
      weaknesses: b.weaknesses,
      sourceFile: b.fileName,
      pageCount: b.pageCount,
    })),
    risks: tender.risks.map((r) => ({
      bidId: r.bidId,
      category: r.category,
      clauseRef: r.clauseRef,
      severity: r.severity,
      title: r.title,
      description: r.description,
      vendorPosition: r.vendorPosition,
      schemaRequirement: r.schemaRequirement,
      pageRef: r.pageRef,
      resolved: r.resolved,
    })),
    clarifications: tender.clarifications.map((round) => ({
      type: round.type,
      number: round.number,
      openedAt: round.openedAt,
      closedAt: round.closedAt,
      dueAt: round.dueAt,
      note: round.note,
      items: round.items.map((i) => ({
        schemaItemRef: i.schemaItemRef,
        bidVendor: i.bid.vendorName,
        question: i.question,
        status: i.status,
        response: i.response,
        respondedAt: i.respondedAt,
        changedItems: i.changedItems,
      })),
    })),
    award: tender.award
      ? {
          recommendedBidId: tender.award.recommendedBidId,
          rationale: tender.award.rationale,
          status: tender.award.status,
          contractValue: tender.award.contractValue,
          currency: tender.award.currency,
          requestedBy: tender.award.requestedBy,
          approvalChain: tender.award.approvalSteps.map((s) => ({
            order: s.order,
            approver: s.approverName,
            role: s.approverRole,
            email: s.approverEmail,
            threshold: s.threshold,
            decision: s.decision,
            decidedAt: s.decidedAt,
            comment: s.comment,
          })),
        }
      : null,
    auditTrail: chain,
    hashChainSummary: {
      algorithm: "SHA-256, prev-hash chain",
      entries: chain.length,
      headHash: prevHash || null,
    },
    disclaimer:
      "Generated by BidLens for procurement defensibility. AI surfaces evidence and risks; humans evaluate and decide. This pack is the immutable evaluation record.",
  };

  const filename = `${tender.reference ?? tender.name}-defensibility-pack.json`
    .replace(/\s+/g, "-")
    .replace(/[^a-zA-Z0-9._-]/g, "");
  return new NextResponse(JSON.stringify(pack, null, 2), {
    status: 200,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "content-disposition": `attachment; filename="${filename}"`,
      "cache-control": "no-store",
    },
  });
}
